name: CI/CD Pipeline

# Trigger the workflow on push to the main/master branch
on:
  push:
    branches:
      - master   # or 'main' if your default branch is main

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Checkout the code from your repository

    - name: Install dependencies (if applicable)
      run: echo "Installing dependencies"
        
    - name: Build Project (if applicable)
      run: echo "Building project..."

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures the build job runs first
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Checkout the code again for deployment

    - name: Deploy to GitHub Pages (or any other deployment platform)
      run: echo "Deploying application..."
