name: CI/CD Pipeline

on:
  push:
    branches:
      - master   # Or 'main' depending on your default branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checkout the code from your repository

      - name: Install dependencies
        run: echo "Installing dependencies"

      - name: Build Project
        run: echo "Building project..."

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures the build job runs first
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checkout the code again for deployment

      - name: Deploy to GitHub Pages
        run: echo "Deploying application..."
